# Generated by Django 6.0.5 on 2026-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_userprofile_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='code_prefix',
            field=models.CharField(blank=True, help_text='Prefijo para los códigos de receta, ej. LT o CV103.', max_length=12),
        ),
    ]
