# Generated by Django 6.0.5 on 2026-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_code_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='default_template',
            field=models.CharField(choices=[('formal', 'Formal'), ('moderna', 'Moderna'), ('tradicional', 'Tradicional'), ('llamativa', 'Llamativa')], default='formal', max_length=20),
        ),
    ]
