# Generated by Django 6.0.5 on 2026-08-13 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restaurant_default_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('business', 'Business')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='plan_status',
            field=models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activa'), ('past_due', 'Impago'), ('suspended', 'Suspendida')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('can_view_recipes', models.BooleanField(default=True)),
                ('can_edit_recipes', models.BooleanField(default=False)),
                ('can_create_recipes', models.BooleanField(default=False)),
                ('can_delete_recipes', models.BooleanField(default=False)),
                ('can_view_escandallo', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('restaurant', 'key'), name='unique_role_key_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_membership_user_restaurant'),
        ),
    ]
