# Generated by Django 6.0.5 on 2026-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_roles_and_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pdf_exports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('basico', 'Básico'), ('pro', 'Premium'), ('business', 'Business')], default='basico', max_length=20),
        ),
    ]
