# Generated by Django 6.0.5 on 2026-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_restaurant_pdf_exports_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tax_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
