# Generated by Django 6.0.5 on 2026-08-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_avatar_planchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchangerequest',
            name='requested_plan',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('basico', 'Básico (Cocinero)'), ('pro', 'Premium'), ('business', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('basico', 'Básico (Cocinero)'), ('pro', 'Premium'), ('business', 'Business')], default='basico', max_length=20),
        ),
    ]
