# Generated by Django 6.0.5 on 2026-08-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_planchangerequest_requested_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar (US$)'), ('GBP', 'Libra (£)'), ('PEN', 'Sol peruano (S/)'), ('MXN', 'Peso mexicano ($)'), ('COP', 'Peso colombiano ($)'), ('ARS', 'Peso argentino ($)'), ('CLP', 'Peso chileno ($)'), ('BRL', 'Real brasileño (R$)')], default='EUR', max_length=3),
        ),
    ]
