# Generated by Django 6.0.5 on 2026-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_restaurant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='carta_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
