# Generated by Django 6.0.5 on 2026-08-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_backfill_public_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='carta_accent_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='carta_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='carta_bg/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='carta_font',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='carta_text_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='carta_theme',
            field=models.CharField(choices=[('marea', 'Marea — oscuro elegante (fine dining)'), ('lienzo', 'Lienzo — bistró claro y cálido (kraft/pizarra)'), ('carbon', 'Carbón — minimal alto contraste (urbano)')], default='marea', max_length=16),
        ),
    ]
