# Generated by Django 6.0.5 on 2026-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_restaurant_carta_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='carta_bg_fx',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='especiales_accent_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='especiales_bg_fx',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='especiales_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='carta_bg/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='especiales_font',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='especiales_text_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='especiales_theme',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
