# Generated by Django 6.0.5 on 2026-08-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_active_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('individual', 'Cocinero particular')], default='restaurant', max_length=20),
        ),
    ]
