# Generated by Django 6.0.5 on 2026-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_restaurant_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
