# Generated by Django 6.0.5 on 2026-08-31 23:10

from django.db import migrations, models


def backfill_owner_locals(apps, schema_editor):
    # Los roles Owner ya existentes conservan la capacidad de gestionar locales.
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(key='owner').update(can_manage_locals=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_locals',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_owner_locals, migrations.RunPython.noop),
    ]
