# Generated by Django 6.0.5 on 2026-08-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_restaurant_pdf_exports_count_and_more'),
        ('catalog', '0003_supplier_address_supplier_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='product',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_qty',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('ud', 'Unidad'), ('pack', 'Pack')], default='kg', max_length=4),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('ud', 'Unidad'), ('pack', 'Pack')], default='ud', max_length=4)),
                ('stock_min', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.partida')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
