# Generated by Django 6.0.5 on 2026-08-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_allergens_remove_product_partida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escandalloline',
            name='escandallo',
        ),
        migrations.RemoveField(
            model_name='escandalloline',
            name='product',
        ),
        migrations.DeleteModel(
            name='Escandallo',
        ),
        migrations.DeleteModel(
            name='EscandalloLine',
        ),
    ]
