# Generated by Django 6.0.5 on 2026-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_escandalloline_escandallo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('ud', 'Unidad'), ('pack', 'Pack')], default='kg', max_length=4),
        ),
    ]
