# Generated by Django 6.0.5 on 2026-08-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_inventoryitem_weight_inventoryitem_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_min_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('ud', 'Unidad'), ('pack', 'Pack')], max_length=4),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='units_per_pack',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight_per_pack',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
