"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables desde backend/.env si existe (solo desarrollo local).
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# SECRET_KEY: en producción se define por variable de entorno.
# El valor por defecto es solo para desarrollo local.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-bm!gb6!jc^6!vh+#6-_-7=27*5s^)g-@53r)z6$yz1q!x5r@a7',
)

# SECURITY WARNING: en producción DEBUG debe ser False (se define en Render).
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'storages',
    'accounts',
    'recipes',
    'catalog',
    'costeo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Si DATABASE_URL está definida (Neon/PostgreSQL) se usa; si no, SQLite local.

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Almacenamiento de archivos (fotos/logos) en Cloudflare R2.
# Si hay credenciales R2, se usa R2; si no, se guardan en disco local (MEDIA_ROOT).
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID')
if R2_ACCESS_KEY_ID:
    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL')
    # Dominio público del bucket (sin https://), ej: pub-xxxx.r2.dev
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('R2_PUBLIC_DOMAIN')
    AWS_S3_REGION_NAME = 'auto'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False   # URLs públicas sin firma
    AWS_S3_FILE_OVERWRITE = False  # no sobreescribir si coincide el nombre
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}

# Dominio público del bucket R2 (custom domain de Cloudflare) para servir las
# imágenes DIRECTAMENTE (rápido, CDN) en vez del proxy /api/media del backend.
# Si está vacío, se usa el proxy (comportamiento anterior). Solo aplica en R2.
R2_PUBLIC_BASE = os.environ.get('R2_PUBLIC_BASE', 'https://img.recipeforge.es') if R2_ACCESS_KEY_ID else ''

# CORS: en local se permite todo; en producción solo los orígenes indicados.
# El dominio propio va FIJO aquí (además de lo que traiga el env) para no
# depender de cambiar variables en Render al conectar recipeforge.es.
_PROD_ORIGINS = ['https://recipeforge.es', 'https://www.recipeforge.es', 'https://app.recipeforge.es']
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys(env_list('CORS_ALLOWED_ORIGINS') + _PROD_ORIGINS))

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(env_list('CSRF_TRUSTED_ORIGINS') + _PROD_ORIGINS))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # ScopedRateThrottle solo limita las vistas que fijan `throttle_scope`
    # (alta autoservicio y reset de contraseña); el resto no se ve afectado.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'signup': '12/hour',
        'password_reset': '12/hour',
    },
}

SIMPLE_JWT = {
    # Sesión larga pensada para cocina: no cerrar sesión a mitad de servicio.
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Seguridad adicional cuando NO estamos en modo desarrollo (producción).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ── Correo transaccional (gateado por configuración) ──────────────────────────
# Envío por SMTP nativo de Django. Compatible con Resend: si defines RESEND_API_KEY
# se autoconfigura smtp.resend.com; o define EMAIL_HOST/USER/PASSWORD a mano.
# Si NO hay credenciales: en DEBUG usa la consola; en producción el backend dummy
# (descarta sin error). El código de envío nunca rompe la petición (send_mail_safe).
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'RecipeForge <info@recipeforge.es>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Destino de los avisos internos (altas nuevas, solicitudes de plan).
ADMIN_NOTIFY_EMAIL = os.environ.get('ADMIN_NOTIFY_EMAIL', 'weltcode@gmail.com')
# Base del frontend para construir enlaces (p. ej. el de restablecer contraseña).
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'https://app.recipeforge.es' if not DEBUG else 'http://localhost:5173')

# Envío por la API HTTP de Resend (puerto 443) cuando hay API key: es lo que
# funciona en PaaS como Render, que bloquean el SMTP saliente (587/465). Si no
# hay key, se usa el backend de Django (consola en DEBUG, dummy en prod).
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()
_RESEND_API_KEY = RESEND_API_KEY
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.resend.com' if _RESEND_API_KEY else '').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'resend' if _RESEND_API_KEY else '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', _RESEND_API_KEY)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = 15

# ¿Hay un canal de envío real configurado?
EMAILS_ENABLED = bool(EMAIL_HOST and EMAIL_HOST_PASSWORD)
if EMAILS_ENABLED:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
elif DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
