# Generated by Django 6.0.5 on 2026-08-18 23:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_restaurant_pdf_exports_count_and_more'),
        ('catalog', '0004_remove_product_allergens_remove_product_partida_and_more'),
        ('recipes', '0014_recipe_allergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_subrecipe', models.BooleanField(default=False)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('yield_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('yield_unit', models.CharField(choices=[('g', 'Gramo (masa)'), ('ml', 'Mililitro (volumen)'), ('ud', 'Unidad (pieza)')], default='g', max_length=4)),
                ('target_food_cost', models.DecimalField(decimal_places=4, default=Decimal('0.30'), max_digits=5)),
                ('iva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_cost_base_snapshot', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costeo_costings', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('base_unit', models.CharField(choices=[('g', 'Gramo (masa)'), ('ml', 'Mililitro (volumen)'), ('ud', 'Unidad (pieza)')], default='g', max_length=4)),
                ('density_g_per_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('weight_per_piece_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cleaning_yield', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6)),
                ('cooking_yield', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costeo_insumos', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=8)),
                ('cleaning_yield_override', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('cooking_yield_override', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costeo.costing')),
                ('subrecipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='costeo.costing')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='costeo.insumo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_includes_iva', models.BooleanField(default=False)),
                ('iva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('pack_levels', models.JSONField(blank=True, default=list)),
                ('unit_size', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('unit_size_unit', models.CharField(default='g', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='costeo.insumo')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supplier')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_includes_iva', models.BooleanField(default=False)),
                ('iva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='costeo.purchaseformat')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='reference_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='costeo.purchaseformat'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_insumo_name_per_restaurant'),
        ),
    ]
