# Generated by Django 6.0.5 on 2026-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='base_unit',
            field=models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilo'), ('ml', 'Mililitro'), ('l', 'Litro'), ('ud', 'Unidad')], default='g', max_length=4),
        ),
    ]
