# Generated by Django 6.0.5 on 2026-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0002_alter_insumo_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='portions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
