# Generated by Django 6.0.5 on 2026-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0003_costing_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='merma_gross',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='merma_net',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
