# Generated by Django 6.0.5 on 2026-08-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0004_insumo_merma_gross_insumo_merma_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='base_unit',
            field=models.CharField(choices=[('g', 'Gramo'), ('kg', 'Kilo'), ('ml', 'Mililitro'), ('l', 'Litro'), ('ud', 'Unidad'), ('pack', 'Pack')], default='g', max_length=4),
        ),
    ]
