# Generated by Django 6.0.3 on 2026-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_final_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='service_temp_c',
        ),
        migrations.AddField(
            model_name='recipe',
            name='shelf_life_unit',
            field=models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses')], default='dias', max_length=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shelf_life_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
