# Generated by Django 6.0.3 on 2026-06-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_replace_service_temp_with_shelf_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_grams',
        ),
        migrations.AddField(
            model_name='recipe',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilos')], default='g', max_length=2),
        ),
    ]
