# Generated by Django 6.0.3 on 2026-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_add_revision_yield_unit_remove_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
