# Generated by Django 6.0.5 on 2026-07-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_userprofile_restaurant'),
        ('recipes', '0006_prep_cook_time_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.restaurant'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('restaurant', 'code'), name='unique_code_per_restaurant'),
        ),
    ]
