# Generated by Django 6.0.5 on 2026-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_seed_leche_de_tigre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
