# Generated by Django 6.0.5 on 2026-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_cook_time_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='template',
            field=models.CharField(choices=[('formal', 'Formal'), ('moderna', 'Moderna'), ('tradicional', 'Tradicional'), ('llamativa', 'Llamativa')], default='formal', max_length=20),
        ),
    ]
