# Generated by Django 6.0.5 on 2026-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='accent_color',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
