# Generated by Django 6.0.5 on 2026-08-18 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('recipes', '0011_recipe_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientline',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_lines', to='catalog.product'),
        ),
    ]
