# Generated by Django 6.0.5 on 2026-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_ingredientline_allergens_ingredientline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
