# Generated by Django 6.0.5 on 2026-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
