# Generated by Django 6.0.5 on 2026-08-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurant_carta_published_restaurant_public_slug'),
        ('recipes', '0014_recipe_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='menu_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_section',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='recipe',
            name='on_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Especial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('sales_pitch', models.TextField(blank=True)),
                ('temperatura', models.CharField(blank=True, choices=[('frio', 'Frío'), ('caliente_tierra', 'Caliente (tierra)'), ('caliente_mar', 'Caliente (mar)')], max_length=16)),
                ('categoria', models.CharField(blank=True, choices=[('entrante', 'Entrante'), ('plato_fuerte', 'Plato fuerte')], max_length=16)),
                ('formato', models.CharField(blank=True, choices=[('individual', 'Individual'), ('compartir', 'Para compartir')], max_length=16)),
                ('para_personas', models.PositiveIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='especial_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especiales', to='accounts.restaurant')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
