# Generated by Django 6.0.5 on 2026-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_menu_description_recipe_menu_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='menu_photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
    ]
